.TH xkb-rs-sp 7 "2026-05-19" 0.0.1 "Qwerty Serbian + Spanish keyboard"
.SH "NAME"
rs-sp - Serbian + Spanish qwerty keyboard mapping
.SH "DESCRIPTION"
Keymap for Serbian users of qwerty keyboard. Also contains spanish symbols
All Serbian characters are directly accessible with AltGr.
.SH "LINKS"
.SS Source repository
https://github.com/bikrtw/us_rs_sp_keyboard

.SH "ENABLING THE RS-SP KEYMAP"
.SS "Command line"
Use the command setxkbmap: setxkbmap us rs-sp

.SH "FILES"
.TP
/etc/X11/xkb/symbols/us
The file containing the mapping of characters.
.SH "SEE ALSO"
setxkbmap(1)
.SH "AUTHOR"
This package is maintained by Igor <bikrtw@gmail.com>.
All files of the package are released under GNU/GPL 2.0 License.

